use_frameworks!
platform :ios, '9.0'

target 'refuge-ios' do

pod 'ADClusterMapView', '1.1.0'
pod 'AFNetworking', '~> 2.5'
pod 'EAIntroView', '2.6.4'
pod 'iRate', '~> 1.11'
pod 'Mantle', '~> 1.5'
pod 'Mixpanel', '~> 2.7'
pod 'Reachability', '~> 3.2'
pod 'HNKGooglePlacesAutocomplete', :git => 'https://github.com/hkellaway/HNKGooglePlacesAutocomplete.git', :branch => 'refuge'

end

