# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'refuge-ios' do

pod 'AFNetworking', '2.5.1'
pod 'Mantle', '1.5.4'
pod 'MBProgressHUD', '0.9'
pod 'Reachability', '3.2'
pod 'SPGooglePlacesAutocomplete', '1.0.4'

end

target 'refuge-iosTests' do

end

link_with 'refuge-ios', 'refuge-iosTests'
