# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RRiOSApp' do

pod 'ADClusterMapView'
pod 'MBProgressHUD', '0.9'
pod 'Reachability', '3.1.1'
pod 'SPGooglePlacesAutocomplete', '1.0.4'

end

target 'RRiOSAppTests' do

end

